[package]
name = "pokemon-rr-save-parser"
version = "0.1.0"
authors = ["Rodrigo Gryzinski <rogryza@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "*"
byteorder = "*"
quick-error = "*"
