[package]
name = "poke3-radicalred-bin"
version = "0.1.0"
authors = ["Rodrigo Gryzinski <rogryza@gmail.com>"]
edition = "2018"

[lib]
name = "poke3_radicalred"
path = "src/lib.rs"

[dependencies]
bitfield = "^0.13.2"
byteorder = "^1.4.3"
serde_json = "1"

poke3-common = { path = "../common" }
